runtime: python39

instance_class: F4

env_variables:
  DATABASE_URL: 'sqlite:////tmp/app.db'
  GCS_BUCKET_NAME: 'org-chart-app-storage'

handlers:
- url: /static
  static_dir: app/static

- url: /.*
  script: auto
