runtime: python39

instance_class: F4

env_variables:
  DB_USER: root
  DB_PASS: ionsolar123
  DB_NAME: OrgChart
  DB_CONNECTION_NAME: new-database-416522:us-central1:org-chart-database
  GCS_BUCKET_NAME: org-chart-app-storage

beta_settings:
  cloud_sql_instances: new-database-416522:us-central1:org-chart-database

handlers:
- url: /static
  static_dir: app/static

- url: /.*
  script: auto
